#ifndef LWCGL_COMPAT_LWJGL3_H
#define LWCGL_COMPAT_LWJGL3_H
#include <lwcgl/lwcgl.h>
/* Opt-in unprefixed OpenGL type/constant aliases for ports that do not include native GL headers. */
typedef LWCGLenum GLenum; typedef LWCGLboolean GLboolean; typedef LWCGLbitfield GLbitfield; typedef LWCGLint GLint; typedef LWCGLsizei GLsizei; typedef LWCGLuint GLuint; typedef LWCGLfloat GLfloat; typedef LWCGLdouble GLdouble; typedef LWCGLchar GLchar; typedef LWCGLintptr GLintptr; typedef LWCGLsizeiptr GLsizeiptr; typedef LWCGLuint64 GLuint64; typedef LWCGLsync GLsync;
#ifndef GL_COLOR_BUFFER_BIT
#define GL_COLOR_BUFFER_BIT LWCGL_GL_COLOR_BUFFER_BIT
#define GL_DEPTH_BUFFER_BIT LWCGL_GL_DEPTH_BUFFER_BIT
#define GL_TRIANGLES LWCGL_GL_TRIANGLES
#define GL_UNSIGNED_BYTE LWCGL_GL_UNSIGNED_BYTE
#define GL_UNSIGNED_INT LWCGL_GL_UNSIGNED_INT
#define GL_FLOAT LWCGL_GL_FLOAT
#define GL_RGBA LWCGL_GL_RGBA
#define GL_TEXTURE_2D LWCGL_GL_TEXTURE_2D
#define GL_TEXTURE_3D LWCGL_GL_TEXTURE_3D
#define GL_ARRAY_BUFFER LWCGL_GL_ARRAY_BUFFER
#define GL_ELEMENT_ARRAY_BUFFER LWCGL_GL_ELEMENT_ARRAY_BUFFER
#define GL_STATIC_DRAW LWCGL_GL_STATIC_DRAW
#define GL_DYNAMIC_DRAW LWCGL_GL_DYNAMIC_DRAW
#define GL_VERTEX_SHADER LWCGL_GL_VERTEX_SHADER
#define GL_FRAGMENT_SHADER LWCGL_GL_FRAGMENT_SHADER
#define GL_COMPUTE_SHADER LWCGL_GL_COMPUTE_SHADER
#define GL_FRAMEBUFFER LWCGL_GL_FRAMEBUFFER
#define GL_COLOR_ATTACHMENT0 LWCGL_GL_COLOR_ATTACHMENT0
#define GL_SHADER_STORAGE_BUFFER LWCGL_GL_SHADER_STORAGE_BUFFER
#define GL_SHADER_IMAGE_ACCESS_BARRIER_BIT LWCGL_GL_SHADER_IMAGE_ACCESS_BARRIER_BIT
#define GL_SHADER_STORAGE_BARRIER_BIT LWCGL_GL_SHADER_STORAGE_BARRIER_BIT
#define GL_COMMAND_BARRIER_BIT LWCGL_GL_COMMAND_BARRIER_BIT
#endif
#ifndef GLFW_TRUE
#define GLFW_TRUE LWCGL_GLFW_TRUE
#define GLFW_FALSE LWCGL_GLFW_FALSE
#define GLFW_VISIBLE LWCGL_GLFW_VISIBLE
#define GLFW_CONTEXT_VERSION_MAJOR LWCGL_GLFW_CONTEXT_VERSION_MAJOR
#define GLFW_CONTEXT_VERSION_MINOR LWCGL_GLFW_CONTEXT_VERSION_MINOR
#define GLFW_OPENGL_PROFILE LWCGL_GLFW_OPENGL_PROFILE
#define GLFW_OPENGL_CORE_PROFILE LWCGL_GLFW_OPENGL_CORE_PROFILE
#define GLFW_OPENGL_COMPAT_PROFILE LWCGL_GLFW_OPENGL_COMPAT_PROFILE
#endif
#endif
