#ifndef LWCGL_OPENGL_H
#define LWCGL_OPENGL_H
#include <lwcgl/common.h>
#include <lwcgl/constants.h>
#ifdef __cplusplus
extern "C" {
#endif
typedef uint32_t LWCGLenum; typedef uint8_t LWCGLboolean; typedef uint32_t LWCGLbitfield; typedef int8_t LWCGLbyte; typedef int16_t LWCGLshort; typedef int32_t LWCGLint; typedef int32_t LWCGLsizei; typedef uint8_t LWCGLubyte; typedef uint16_t LWCGLushort; typedef uint32_t LWCGLuint; typedef float LWCGLfloat; typedef double LWCGLdouble; typedef ptrdiff_t LWCGLintptr; typedef ptrdiff_t LWCGLsizeiptr; typedef int64_t LWCGLint64; typedef uint64_t LWCGLuint64; typedef char LWCGLchar; typedef struct LWCGLsyncHandle *LWCGLsync;
typedef void (*LWCGLDEBUGPROC)(LWCGLenum,LWCGLenum,LWCGLuint,LWCGLenum,LWCGLsizei,const LWCGLchar*,const void*);
typedef struct GL11API { void(*glClear)(LWCGLbitfield); void(*glClearColor)(LWCGLfloat,LWCGLfloat,LWCGLfloat,LWCGLfloat); void(*glClearDepth)(LWCGLdouble); void(*glViewport)(LWCGLint,LWCGLint,LWCGLsizei,LWCGLsizei); void(*glScissor)(LWCGLint,LWCGLint,LWCGLsizei,LWCGLsizei); void(*glEnable)(LWCGLenum); void(*glDisable)(LWCGLenum); LWCGLboolean(*glIsEnabled)(LWCGLenum); void(*glBlendFunc)(LWCGLenum,LWCGLenum); void(*glDepthFunc)(LWCGLenum); void(*glDepthMask)(LWCGLboolean); void(*glColorMask)(LWCGLboolean,LWCGLboolean,LWCGLboolean,LWCGLboolean); void(*glCullFace)(LWCGLenum); void(*glFrontFace)(LWCGLenum); void(*glPolygonMode)(LWCGLenum,LWCGLenum); void(*glLineWidth)(LWCGLfloat); void(*glPointSize)(LWCGLfloat); void(*glDrawArrays)(LWCGLenum,LWCGLint,LWCGLsizei); void(*glDrawElements)(LWCGLenum,LWCGLsizei,LWCGLenum,const void*); void(*glGenTextures)(LWCGLsizei,LWCGLuint*); void(*glDeleteTextures)(LWCGLsizei,const LWCGLuint*); void(*glBindTexture)(LWCGLenum,LWCGLuint); void(*glTexParameteri)(LWCGLenum,LWCGLenum,LWCGLint); void(*glTexParameterf)(LWCGLenum,LWCGLenum,LWCGLfloat); void(*glTexImage2D)(LWCGLenum,LWCGLint,LWCGLint,LWCGLsizei,LWCGLsizei,LWCGLint,LWCGLenum,LWCGLenum,const void*); void(*glTexSubImage2D)(LWCGLenum,LWCGLint,LWCGLint,LWCGLint,LWCGLsizei,LWCGLsizei,LWCGLenum,LWCGLenum,const void*); const LWCGLubyte*(*glGetString)(LWCGLenum); void(*glGetBooleanv)(LWCGLenum,LWCGLboolean*); void(*glGetIntegerv)(LWCGLenum,LWCGLint*); void(*glGetFloatv)(LWCGLenum,LWCGLfloat*); LWCGLenum(*glGetError)(void); void(*glReadPixels)(LWCGLint,LWCGLint,LWCGLsizei,LWCGLsizei,LWCGLenum,LWCGLenum,void*); void(*glPixelStorei)(LWCGLenum,LWCGLint); } GL11API;
typedef struct GL12API { void(*glDrawRangeElements)(LWCGLenum,LWCGLuint,LWCGLuint,LWCGLsizei,LWCGLenum,const void*); void(*glTexImage3D)(LWCGLenum,LWCGLint,LWCGLint,LWCGLsizei,LWCGLsizei,LWCGLsizei,LWCGLint,LWCGLenum,LWCGLenum,const void*); void(*glTexSubImage3D)(LWCGLenum,LWCGLint,LWCGLint,LWCGLint,LWCGLint,LWCGLsizei,LWCGLsizei,LWCGLsizei,LWCGLenum,LWCGLenum,const void*); } GL12API;
typedef struct GL13API { void(*glActiveTexture)(LWCGLenum); void(*glSampleCoverage)(LWCGLfloat,LWCGLboolean); void(*glCompressedTexImage2D)(LWCGLenum,LWCGLint,LWCGLenum,LWCGLsizei,LWCGLsizei,LWCGLint,LWCGLsizei,const void*); } GL13API;
typedef struct GL14API { void(*glBlendEquation)(LWCGLenum); void(*glBlendFuncSeparate)(LWCGLenum,LWCGLenum,LWCGLenum,LWCGLenum); void(*glPointParameterf)(LWCGLenum,LWCGLfloat); void(*glPointParameterfv)(LWCGLenum,const LWCGLfloat*); } GL14API;
typedef struct GL15API { void(*glGenBuffers)(LWCGLsizei,LWCGLuint*); void(*glDeleteBuffers)(LWCGLsizei,const LWCGLuint*); void(*glBindBuffer)(LWCGLenum,LWCGLuint); void(*glBufferData)(LWCGLenum,LWCGLsizeiptr,const void*,LWCGLenum); void(*glBufferSubData)(LWCGLenum,LWCGLintptr,LWCGLsizeiptr,const void*); void(*glGetBufferSubData)(LWCGLenum,LWCGLintptr,LWCGLsizeiptr,void*); void*(*glMapBuffer)(LWCGLenum,LWCGLenum); LWCGLboolean(*glUnmapBuffer)(LWCGLenum); void(*glGenQueries)(LWCGLsizei,LWCGLuint*); void(*glDeleteQueries)(LWCGLsizei,const LWCGLuint*); void(*glBeginQuery)(LWCGLenum,LWCGLuint); void(*glEndQuery)(LWCGLenum); void(*glGetQueryObjectuiv)(LWCGLuint,LWCGLenum,LWCGLuint*); } GL15API;
typedef struct GL20API { LWCGLuint(*glCreateShader)(LWCGLenum); void(*glShaderSource)(LWCGLuint,LWCGLsizei,const LWCGLchar*const*,const LWCGLint*); void(*glCompileShader)(LWCGLuint); void(*glGetShaderiv)(LWCGLuint,LWCGLenum,LWCGLint*); void(*glGetShaderInfoLog)(LWCGLuint,LWCGLsizei,LWCGLsizei*,LWCGLchar*); void(*glDeleteShader)(LWCGLuint); LWCGLuint(*glCreateProgram)(void); void(*glAttachShader)(LWCGLuint,LWCGLuint); void(*glDetachShader)(LWCGLuint,LWCGLuint); void(*glLinkProgram)(LWCGLuint); void(*glValidateProgram)(LWCGLuint); void(*glGetProgramiv)(LWCGLuint,LWCGLenum,LWCGLint*); void(*glGetProgramInfoLog)(LWCGLuint,LWCGLsizei,LWCGLsizei*,LWCGLchar*); void(*glUseProgram)(LWCGLuint); void(*glDeleteProgram)(LWCGLuint); LWCGLint(*glGetUniformLocation)(LWCGLuint,const LWCGLchar*); void(*glUniform1i)(LWCGLint,LWCGLint); void(*glUniform1f)(LWCGLint,LWCGLfloat); void(*glUniform2f)(LWCGLint,LWCGLfloat,LWCGLfloat); void(*glUniform3f)(LWCGLint,LWCGLfloat,LWCGLfloat,LWCGLfloat); void(*glUniform4f)(LWCGLint,LWCGLfloat,LWCGLfloat,LWCGLfloat,LWCGLfloat); void(*glUniformMatrix4fv)(LWCGLint,LWCGLsizei,LWCGLboolean,const LWCGLfloat*); LWCGLint(*glGetAttribLocation)(LWCGLuint,const LWCGLchar*); void(*glBindAttribLocation)(LWCGLuint,LWCGLuint,const LWCGLchar*); void(*glEnableVertexAttribArray)(LWCGLuint); void(*glDisableVertexAttribArray)(LWCGLuint); void(*glVertexAttribPointer)(LWCGLuint,LWCGLint,LWCGLenum,LWCGLboolean,LWCGLsizei,const void*); void(*glDrawBuffers)(LWCGLsizei,const LWCGLenum*); } GL20API;
typedef struct GL21API { void(*glUniformMatrix2x3fv)(LWCGLint,LWCGLsizei,LWCGLboolean,const LWCGLfloat*); void(*glUniformMatrix3x2fv)(LWCGLint,LWCGLsizei,LWCGLboolean,const LWCGLfloat*); } GL21API;
typedef struct GL30API { void(*glGenVertexArrays)(LWCGLsizei,LWCGLuint*); void(*glDeleteVertexArrays)(LWCGLsizei,const LWCGLuint*); void(*glBindVertexArray)(LWCGLuint); LWCGLboolean(*glIsVertexArray)(LWCGLuint); void*(*glMapBufferRange)(LWCGLenum,LWCGLintptr,LWCGLsizeiptr,LWCGLbitfield); void(*glFlushMappedBufferRange)(LWCGLenum,LWCGLintptr,LWCGLsizeiptr); void(*glGenFramebuffers)(LWCGLsizei,LWCGLuint*); void(*glDeleteFramebuffers)(LWCGLsizei,const LWCGLuint*); void(*glBindFramebuffer)(LWCGLenum,LWCGLuint); LWCGLenum(*glCheckFramebufferStatus)(LWCGLenum); void(*glFramebufferTexture2D)(LWCGLenum,LWCGLenum,LWCGLenum,LWCGLuint,LWCGLint); void(*glFramebufferTextureLayer)(LWCGLenum,LWCGLenum,LWCGLuint,LWCGLint,LWCGLint); void(*glGenRenderbuffers)(LWCGLsizei,LWCGLuint*); void(*glDeleteRenderbuffers)(LWCGLsizei,const LWCGLuint*); void(*glBindRenderbuffer)(LWCGLenum,LWCGLuint); void(*glRenderbufferStorage)(LWCGLenum,LWCGLenum,LWCGLsizei,LWCGLsizei); void(*glFramebufferRenderbuffer)(LWCGLenum,LWCGLenum,LWCGLenum,LWCGLuint); void(*glGenerateMipmap)(LWCGLenum); void(*glBlitFramebuffer)(LWCGLint,LWCGLint,LWCGLint,LWCGLint,LWCGLint,LWCGLint,LWCGLint,LWCGLint,LWCGLbitfield,LWCGLenum); void(*glRenderbufferStorageMultisample)(LWCGLenum,LWCGLsizei,LWCGLenum,LWCGLsizei,LWCGLsizei); void(*glBindBufferBase)(LWCGLenum,LWCGLuint,LWCGLuint); void(*glBindBufferRange)(LWCGLenum,LWCGLuint,LWCGLuint,LWCGLintptr,LWCGLsizeiptr); const LWCGLubyte*(*glGetStringi)(LWCGLenum,LWCGLuint); } GL30API;
typedef struct GL31API { void(*glDrawArraysInstanced)(LWCGLenum,LWCGLint,LWCGLsizei,LWCGLsizei); void(*glDrawElementsInstanced)(LWCGLenum,LWCGLsizei,LWCGLenum,const void*,LWCGLsizei); void(*glCopyBufferSubData)(LWCGLenum,LWCGLenum,LWCGLintptr,LWCGLintptr,LWCGLsizeiptr); LWCGLuint(*glGetUniformBlockIndex)(LWCGLuint,const LWCGLchar*); void(*glUniformBlockBinding)(LWCGLuint,LWCGLuint,LWCGLuint); } GL31API;
typedef struct GL32API { LWCGLsync(*glFenceSync)(LWCGLenum,LWCGLbitfield); LWCGLboolean(*glIsSync)(LWCGLsync); void(*glDeleteSync)(LWCGLsync); LWCGLenum(*glClientWaitSync)(LWCGLsync,LWCGLbitfield,LWCGLuint64); void(*glWaitSync)(LWCGLsync,LWCGLbitfield,LWCGLuint64); void(*glDrawElementsBaseVertex)(LWCGLenum,LWCGLsizei,LWCGLenum,const void*,LWCGLint); } GL32API;
typedef struct GL33API { void(*glVertexAttribDivisor)(LWCGLuint,LWCGLuint); void(*glGenSamplers)(LWCGLsizei,LWCGLuint*); void(*glDeleteSamplers)(LWCGLsizei,const LWCGLuint*); void(*glBindSampler)(LWCGLuint,LWCGLuint); void(*glSamplerParameteri)(LWCGLuint,LWCGLenum,LWCGLint); void(*glQueryCounter)(LWCGLuint,LWCGLenum); void(*glGetQueryObjectui64v)(LWCGLuint,LWCGLenum,LWCGLuint64*); } GL33API;
typedef struct GL40API { void(*glDrawArraysIndirect)(LWCGLenum,const void*); void(*glDrawElementsIndirect)(LWCGLenum,LWCGLenum,const void*); void(*glPatchParameteri)(LWCGLenum,LWCGLint); void(*glBlendEquationi)(LWCGLuint,LWCGLenum); void(*glBlendFunci)(LWCGLuint,LWCGLenum,LWCGLenum); } GL40API;
typedef struct GL41API { void(*glGenProgramPipelines)(LWCGLsizei,LWCGLuint*); void(*glDeleteProgramPipelines)(LWCGLsizei,const LWCGLuint*); void(*glBindProgramPipeline)(LWCGLuint); void(*glUseProgramStages)(LWCGLuint,LWCGLbitfield,LWCGLuint); void(*glProgramUniform1i)(LWCGLuint,LWCGLint,LWCGLint); void(*glProgramUniform1f)(LWCGLuint,LWCGLint,LWCGLfloat); void(*glProgramUniformMatrix4fv)(LWCGLuint,LWCGLint,LWCGLsizei,LWCGLboolean,const LWCGLfloat*); void(*glShaderBinary)(LWCGLsizei,const LWCGLuint*,LWCGLenum,const void*,LWCGLsizei); } GL41API;
typedef struct GL42API { void(*glMemoryBarrier)(LWCGLbitfield); void(*glTexStorage1D)(LWCGLenum,LWCGLsizei,LWCGLenum,LWCGLsizei); void(*glTexStorage2D)(LWCGLenum,LWCGLsizei,LWCGLenum,LWCGLsizei,LWCGLsizei); void(*glTexStorage3D)(LWCGLenum,LWCGLsizei,LWCGLenum,LWCGLsizei,LWCGLsizei,LWCGLsizei); void(*glBindImageTexture)(LWCGLuint,LWCGLuint,LWCGLint,LWCGLboolean,LWCGLint,LWCGLenum,LWCGLenum); } GL42API;
typedef struct GL43API { void(*glDispatchCompute)(LWCGLuint,LWCGLuint,LWCGLuint); void(*glDispatchComputeIndirect)(LWCGLintptr); void(*glDebugMessageCallback)(LWCGLDEBUGPROC,const void*); void(*glDebugMessageControl)(LWCGLenum,LWCGLenum,LWCGLenum,LWCGLsizei,const LWCGLuint*,LWCGLboolean); void(*glObjectLabel)(LWCGLenum,LWCGLuint,LWCGLsizei,const LWCGLchar*); void(*glMultiDrawArraysIndirect)(LWCGLenum,const void*,LWCGLsizei,LWCGLsizei); void(*glMultiDrawElementsIndirect)(LWCGLenum,LWCGLenum,const void*,LWCGLsizei,LWCGLsizei); } GL43API;
typedef struct GL44API { void(*glBufferStorage)(LWCGLenum,LWCGLsizeiptr,const void*,LWCGLbitfield); void(*glBindBuffersBase)(LWCGLenum,LWCGLuint,LWCGLsizei,const LWCGLuint*); void(*glBindTextures)(LWCGLuint,LWCGLsizei,const LWCGLuint*); void(*glBindSamplers)(LWCGLuint,LWCGLsizei,const LWCGLuint*); void(*glClearTexImage)(LWCGLuint,LWCGLint,LWCGLenum,LWCGLenum,const void*); } GL44API;
typedef struct GL45API { void(*glCreateBuffers)(LWCGLsizei,LWCGLuint*); void(*glNamedBufferData)(LWCGLuint,LWCGLsizeiptr,const void*,LWCGLenum); void(*glNamedBufferStorage)(LWCGLuint,LWCGLsizeiptr,const void*,LWCGLbitfield); void(*glNamedBufferSubData)(LWCGLuint,LWCGLintptr,LWCGLsizeiptr,const void*); void(*glCreateVertexArrays)(LWCGLsizei,LWCGLuint*); void(*glCreateTextures)(LWCGLenum,LWCGLsizei,LWCGLuint*); void(*glTextureStorage2D)(LWCGLuint,LWCGLsizei,LWCGLenum,LWCGLsizei,LWCGLsizei); void(*glTextureSubImage2D)(LWCGLuint,LWCGLint,LWCGLint,LWCGLint,LWCGLsizei,LWCGLsizei,LWCGLenum,LWCGLenum,const void*); void(*glBindTextureUnit)(LWCGLuint,LWCGLuint); void(*glCreateFramebuffers)(LWCGLsizei,LWCGLuint*); void(*glNamedFramebufferTexture)(LWCGLuint,LWCGLenum,LWCGLuint,LWCGLint); LWCGLenum(*glCheckNamedFramebufferStatus)(LWCGLuint,LWCGLenum); void(*glClipControl)(LWCGLenum,LWCGLenum); } GL45API;
typedef struct GL46API { void(*glSpecializeShader)(LWCGLuint,const LWCGLchar*,LWCGLuint,const LWCGLuint*,const LWCGLuint*); void(*glMultiDrawArraysIndirectCount)(LWCGLenum,const void*,LWCGLintptr,LWCGLsizei,LWCGLsizei); void(*glMultiDrawElementsIndirectCount)(LWCGLenum,LWCGLenum,const void*,LWCGLintptr,LWCGLsizei,LWCGLsizei); } GL46API;
typedef struct GLCapabilities { size_t abiSize; uint32_t abiVersion; int major,minor; void *context; uint64_t contextGeneration; LWCGLbool OpenGL11,OpenGL12,OpenGL13,OpenGL14,OpenGL15,OpenGL20,OpenGL21,OpenGL30,OpenGL31,OpenGL32,OpenGL33,OpenGL40,OpenGL41,OpenGL42,OpenGL43,OpenGL44,OpenGL45,OpenGL46; GL11API GL11; GL12API GL12; GL13API GL13; GL14API GL14; GL15API GL15; GL20API GL20; GL21API GL21; GL30API GL30; GL31API GL31; GL32API GL32; GL33API GL33; GL40API GL40; GL41API GL41; GL42API GL42; GL43API GL43; GL44API GL44; GL45API GL45; GL46API GL46; void *internal; } GLCapabilities;
typedef struct LWCGLGLAPI { size_t abiSize; uint32_t abiVersion; GLCapabilities*(*createCapabilities)(void); void(*destroyCapabilities)(GLCapabilities*); GLCapabilities*(*getCapabilities)(void); int(*setCapabilities)(GLCapabilities*); void*(*getFunctionAddress)(const char*); LWCGLbool(*isFunctionAvailable)(const char*); LWCGLbool(*isExtensionSupported)(const char*); } LWCGLGLAPI;
#ifndef GLAPI
typedef LWCGLGLAPI GLAPI;
#endif
extern const LWCGLGLAPI GL;
extern LWCGL_THREAD_LOCAL GL11API GL11; extern LWCGL_THREAD_LOCAL GL12API GL12; extern LWCGL_THREAD_LOCAL GL13API GL13; extern LWCGL_THREAD_LOCAL GL14API GL14; extern LWCGL_THREAD_LOCAL GL15API GL15; extern LWCGL_THREAD_LOCAL GL20API GL20; extern LWCGL_THREAD_LOCAL GL21API GL21; extern LWCGL_THREAD_LOCAL GL30API GL30; extern LWCGL_THREAD_LOCAL GL31API GL31; extern LWCGL_THREAD_LOCAL GL32API GL32; extern LWCGL_THREAD_LOCAL GL33API GL33; extern LWCGL_THREAD_LOCAL GL40API GL40; extern LWCGL_THREAD_LOCAL GL41API GL41; extern LWCGL_THREAD_LOCAL GL42API GL42; extern LWCGL_THREAD_LOCAL GL43API GL43; extern LWCGL_THREAD_LOCAL GL44API GL44; extern LWCGL_THREAD_LOCAL GL45API GL45; extern LWCGL_THREAD_LOCAL GL46API GL46;
#ifdef __cplusplus
}
#endif
#endif
