#include <lwcgl/lwcgl.h>
#include "lwcgl_internal.h"
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <string.h>
static int w_init(void){lwcglClearError();int ok=glfwInit();if(!ok)lwcglSetErrorInternal(LWCGL_ERROR_NATIVE,"glfwInit failed");return ok;}
static void w_term(void){lwcglGLInvalidateAllContexts();glfwTerminate();}
static void w_getver(int*a,int*b,int*c){glfwGetVersion(a,b,c);} static const char*w_verstr(void){return glfwGetVersionString();} static int w_err(const char**d){return glfwGetError(d);} static LWCGLFWerrorfun w_errcb(LWCGLFWerrorfun cb){return (LWCGLFWerrorfun)glfwSetErrorCallback((GLFWerrorfun)cb);}
static LWCGLFWmonitor **w_mons(int*n){return (LWCGLFWmonitor**)glfwGetMonitors(n);} static LWCGLFWmonitor*w_primary(void){return (LWCGLFWmonitor*)glfwGetPrimaryMonitor();}
static void w_mpos(LWCGLFWmonitor*m,int*x,int*y){glfwGetMonitorPos((GLFWmonitor*)m,x,y);} static void w_work(LWCGLFWmonitor*m,int*x,int*y,int*w,int*h){glfwGetMonitorWorkarea((GLFWmonitor*)m,x,y,w,h);} static void w_phys(LWCGLFWmonitor*m,int*w,int*h){glfwGetMonitorPhysicalSize((GLFWmonitor*)m,w,h);} static void w_mscale(LWCGLFWmonitor*m,float*x,float*y){glfwGetMonitorContentScale((GLFWmonitor*)m,x,y);} static const char*w_mname(LWCGLFWmonitor*m){return glfwGetMonitorName((GLFWmonitor*)m);} static const LWCGLFWvidmode*w_modes(LWCGLFWmonitor*m,int*n){return (const LWCGLFWvidmode*)glfwGetVideoModes((GLFWmonitor*)m,n);} static const LWCGLFWvidmode*w_mode(LWCGLFWmonitor*m){return (const LWCGLFWvidmode*)glfwGetVideoMode((GLFWmonitor*)m);}
static void w_defaults(void){glfwDefaultWindowHints();} static void w_hint(int h,int v){glfwWindowHint(h,v);} static LWCGLFWwindow*w_create(int width,int height,const char*t,LWCGLFWmonitor*m,LWCGLFWwindow*s){GLFWwindow*w=glfwCreateWindow(width,height,t,(GLFWmonitor*)m,(GLFWwindow*)s);if(w)lwcglGLRegisterContext(w);else lwcglSetErrorInternal(LWCGL_ERROR_NATIVE,"glfwCreateWindow failed");return (LWCGLFWwindow*)w;} static void w_destroy(LWCGLFWwindow*w){if(!w)return;lwcglGLUnregisterContext(w);glfwDestroyWindow((GLFWwindow*)w);} static int w_should(LWCGLFWwindow*w){return glfwWindowShouldClose((GLFWwindow*)w);} static void w_setshould(LWCGLFWwindow*w,int v){glfwSetWindowShouldClose((GLFWwindow*)w,v);} static void w_title(LWCGLFWwindow*w,const char*t){glfwSetWindowTitle((GLFWwindow*)w,t);} static void w_icon(LWCGLFWwindow*w,int n,const LWCGLFWimage*i){glfwSetWindowIcon((GLFWwindow*)w,n,(const GLFWimage*)i);} static void w_size(LWCGLFWwindow*w,int*x,int*y){glfwGetWindowSize((GLFWwindow*)w,x,y);} static void w_fbsize(LWCGLFWwindow*w,int*x,int*y){glfwGetFramebufferSize((GLFWwindow*)w,x,y);} static LWCGLFWmonitor*w_wmon(LWCGLFWwindow*w){return (LWCGLFWmonitor*)glfwGetWindowMonitor((GLFWwindow*)w);} static void w_setmon(LWCGLFWwindow*w,LWCGLFWmonitor*m,int x,int y,int width,int height,int refresh){glfwSetWindowMonitor((GLFWwindow*)w,(GLFWmonitor*)m,x,y,width,height,refresh);}
static void w_poll(void){glfwPollEvents();} static void w_wait(double t){glfwWaitEventsTimeout(t);} static int w_getim(LWCGLFWwindow*w,int m){return glfwGetInputMode((GLFWwindow*)w,m);} static void w_setim(LWCGLFWwindow*w,int m,int v){glfwSetInputMode((GLFWwindow*)w,m,v);} static int w_key(LWCGLFWwindow*w,int k){return glfwGetKey((GLFWwindow*)w,k);} static int w_button(LWCGLFWwindow*w,int b){return glfwGetMouseButton((GLFWwindow*)w,b);} static void w_cpos(LWCGLFWwindow*w,double*x,double*y){glfwGetCursorPos((GLFWwindow*)w,x,y);} static void w_setcpos(LWCGLFWwindow*w,double x,double y){glfwSetCursorPos((GLFWwindow*)w,x,y);} static LWCGLFWcursor*w_cursor(const LWCGLFWimage*i,int x,int y){return (LWCGLFWcursor*)glfwCreateCursor((const GLFWimage*)i,x,y);} static LWCGLFWcursor*w_stdcur(int s){return (LWCGLFWcursor*)glfwCreateStandardCursor(s);} static void w_delcur(LWCGLFWcursor*c){glfwDestroyCursor((GLFWcursor*)c);} static void w_setcur(LWCGLFWwindow*w,LWCGLFWcursor*c){glfwSetCursor((GLFWwindow*)w,(GLFWcursor*)c);}
static LWCGLFWkeyfun w_keycb(LWCGLFWwindow*w,LWCGLFWkeyfun f){return (LWCGLFWkeyfun)glfwSetKeyCallback((GLFWwindow*)w,(GLFWkeyfun)f);} static LWCGLFWcharfun w_charcb(LWCGLFWwindow*w,LWCGLFWcharfun f){return (LWCGLFWcharfun)glfwSetCharCallback((GLFWwindow*)w,(GLFWcharfun)f);} static LWCGLFWmousebuttonfun w_btncb(LWCGLFWwindow*w,LWCGLFWmousebuttonfun f){return (LWCGLFWmousebuttonfun)glfwSetMouseButtonCallback((GLFWwindow*)w,(GLFWmousebuttonfun)f);} static LWCGLFWcursorposfun w_poscb(LWCGLFWwindow*w,LWCGLFWcursorposfun f){return (LWCGLFWcursorposfun)glfwSetCursorPosCallback((GLFWwindow*)w,(GLFWcursorposfun)f);} static LWCGLFWscrollfun w_scrollcb(LWCGLFWwindow*w,LWCGLFWscrollfun f){return (LWCGLFWscrollfun)glfwSetScrollCallback((GLFWwindow*)w,(GLFWscrollfun)f);}
static int w_jpresent(int j){return glfwJoystickPresent(j);} static int w_jgamepad(int j){return glfwJoystickIsGamepad(j);} static LWCGLFWjoystickfun w_jcb(LWCGLFWjoystickfun f){return (LWCGLFWjoystickfun)glfwSetJoystickCallback((GLFWjoystickfun)f);} static const char*w_gname(int j){return glfwGetGamepadName(j);} static int w_gstate(int j,LWCGLFWgamepadstate*s){return glfwGetGamepadState(j,(GLFWgamepadstate*)s);}
static void w_clipset(LWCGLFWwindow*w,const char*s){glfwSetClipboardString((GLFWwindow*)w,s);} static const char*w_clipget(LWCGLFWwindow*w){return glfwGetClipboardString((GLFWwindow*)w);} static double w_time(void){return glfwGetTime();} static uint64_t w_timer(void){return glfwGetTimerValue();} static uint64_t w_freq(void){return glfwGetTimerFrequency();}
static void w_make(LWCGLFWwindow*w){glfwMakeContextCurrent((GLFWwindow*)w);lwcglGLContextChanged(w);} static LWCGLFWwindow*w_current(void){return (LWCGLFWwindow*)glfwGetCurrentContext();} static void w_swap(LWCGLFWwindow*w){glfwSwapBuffers((GLFWwindow*)w);} static void w_interval(int i){glfwSwapInterval(i);} static int w_ext(const char*s){return glfwExtensionSupported(s);} static LWCGLFWglproc w_proc(const char*s){return (LWCGLFWglproc)glfwGetProcAddress(s);}
const LWCGLFWAPI GLFW={sizeof(LWCGLFWAPI),LWCGL_ABI_VERSION,w_init,w_term,w_getver,w_verstr,w_err,w_errcb,w_mons,w_primary,w_mpos,w_work,w_phys,w_mscale,w_mname,w_modes,w_mode,w_defaults,w_hint,w_create,w_destroy,w_should,w_setshould,w_title,w_icon,w_size,w_fbsize,w_wmon,w_setmon,w_poll,w_wait,w_getim,w_setim,w_key,w_button,w_cpos,w_setcpos,w_cursor,w_stdcur,w_delcur,w_setcur,w_keycb,w_charcb,w_btncb,w_poscb,w_scrollcb,w_jpresent,w_jgamepad,w_jcb,w_gname,w_gstate,w_clipset,w_clipget,w_time,w_timer,w_freq,w_make,w_current,w_swap,w_interval,w_ext,w_proc};
int lwcglGLFWVersionSupported(void){int a=0,b=0,c=0;glfwGetVersion(&a,&b,&c);(void)c;return a>3||(a==3&&b>=3);}
int lwcglGLFWFeatureAvailable(LWCGLFWFeature f){if(!lwcglGLFWVersionSupported())return 0;switch(f){case LWCGL_GLFW_FEATURE_MONITOR_WORKAREA:case LWCGL_GLFW_FEATURE_CONTENT_SCALE:case LWCGL_GLFW_FEATURE_GAMEPAD:case LWCGL_GLFW_FEATURE_CURSOR:return 1;default:return 0;}}
