#define LWCGL_IMPLEMENTATION
#include <lwcgl/lwcgl.h>
#include "internal.h"
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#define EVENT_CAPACITY 1024u
#define BUTTON_CAPACITY 16

typedef struct MouseEvent{int button;LWCGLbool state;int dx,dy,x,y,wheel;uint64_t nanos;}MouseEvent;
static MouseEvent events[EVENT_CAPACITY],current;static size_t read_pos,write_pos;static GLFWcursorposfun chained_cursor;static GLFWmousebuttonfun chained_button;static GLFWscrollfun chained_scroll;static LWCGLbool created,grabbed,clip=LWCGL_TRUE,have_position,ignore_cursor;static double mouse_x,mouse_y,dx_accum,dy_accum,event_dx_frac,event_dy_frac,wheel_accum,event_wheel_frac;static unsigned char buttons[BUTTON_CAPACITY];static uint64_t dropped;
static GLFWwindow*w(void){return(GLFWwindow*)Display.getNativeWindow();}
static void push(MouseEvent e){size_t next=(write_pos+1u)%EVENT_CAPACITY;if(next==read_pos){read_pos=(read_pos+1u)%EVENT_CAPACITY;dropped++;}events[write_pos]=e;write_pos=next;}
static void scale(double x,double y,double*sx,double*sy){int ww=1,wh=1,fw=Display.getWidth(),fh=Display.getHeight();GLFWwindow*win=w();if(win)glfwGetWindowSize(win,&ww,&wh);if(ww<=0)ww=1;if(wh<=0)wh=1;*sx=x*(double)fw/(double)ww;*sy=y*(double)fh/(double)wh;}
static int public_x(double x){double sx,sy;scale(x,mouse_y,&sx,&sy);(void)sy;int out=(int)floor(sx),width=Display.getWidth();if(clip){if(out<0)out=0;if(out>=width)out=width>0?width-1:0;}return out;}
static int public_y(double y){double sx,sy;scale(mouse_x,y,&sx,&sy);(void)sx;int height=Display.getHeight(),out=height-1-(int)floor(sy);if(clip){if(out<0)out=0;if(out>=height)out=height>0?height-1:0;}return out;}
static int whole(double*v){int out=(int)trunc(*v);*v-=(double)out;return out;}
static void cursor_callback(GLFWwindow*win,double x,double y){(void)win;if(!created)return;if(ignore_cursor){ignore_cursor=LWCGL_FALSE;mouse_x=x;mouse_y=y;have_position=LWCGL_TRUE;return;}double dx=0,dy=0;if(have_position){double ox,oy,nx,ny;scale(mouse_x,mouse_y,&ox,&oy);scale(x,y,&nx,&ny);dx=nx-ox;dy=oy-ny;}mouse_x=x;mouse_y=y;have_position=LWCGL_TRUE;dx_accum+=dx;dy_accum+=dy;event_dx_frac+=dx;event_dy_frac+=dy;push((MouseEvent){-1,LWCGL_FALSE,whole(&event_dx_frac),whole(&event_dy_frac),public_x(x),public_y(y),0,lwcglNanoTime()});if(chained_cursor)chained_cursor(win,x,y);}
static void button_callback(GLFWwindow*win,int button,int action,int mods){(void)win;(void)mods;if(!created)return;if(button>=0&&button<BUTTON_CAPACITY)buttons[button]=(unsigned char)(action!=GLFW_RELEASE);push((MouseEvent){button,action!=GLFW_RELEASE,0,0,public_x(mouse_x),public_y(mouse_y),0,lwcglNanoTime()});if(chained_button)chained_button(win,button,action,mods);}
static void scroll_callback(GLFWwindow*win,double xoff,double yoff){(void)win;(void)xoff;if(!created)return;double delta=yoff*120.0;wheel_accum+=delta;event_wheel_frac+=delta;push((MouseEvent){-1,LWCGL_FALSE,0,0,public_x(mouse_x),public_y(mouse_y),whole(&event_wheel_frac),lwcglNanoTime()});if(chained_scroll)chained_scroll(win,xoff,yoff);}
static int create_mouse(void){GLFWwindow*win=w();if(!win){lwcglSetErrorInternal("Mouse.create requires Display.create first");return -1;}if(created)return 0;memset(buttons,0,sizeof buttons);read_pos=write_pos=0;dx_accum=dy_accum=event_dx_frac=event_dy_frac=wheel_accum=event_wheel_frac=0;created=LWCGL_TRUE;chained_cursor=glfwSetCursorPosCallback(win,cursor_callback);chained_button=glfwSetMouseButtonCallback(win,button_callback);chained_scroll=glfwSetScrollCallback(win,scroll_callback);glfwGetCursorPos(win,&mouse_x,&mouse_y);have_position=LWCGL_TRUE;for(int i=0;i<BUTTON_CAPACITY;i++)buttons[i]=(unsigned char)(glfwGetMouseButton(win,i)==GLFW_PRESS);return 0;}
void lwcglMouseForceDestroy(void){GLFWwindow*win=w();if(created&&win){glfwSetCursorPosCallback(win,chained_cursor);glfwSetMouseButtonCallback(win,chained_button);glfwSetScrollCallback(win,chained_scroll);glfwSetInputMode(win,GLFW_CURSOR,GLFW_CURSOR_NORMAL);}chained_cursor=NULL;chained_button=NULL;chained_scroll=NULL;created=LWCGL_FALSE;grabbed=LWCGL_FALSE;read_pos=write_pos=0;have_position=LWCGL_FALSE;memset(buttons,0,sizeof buttons);}
static void destroy_mouse(void){lwcglMouseForceDestroy();}static LWCGLbool is_created(void){return created;}static void poll(void){if(w())glfwPollEvents();}static LWCGLbool button_down(int b){return b>=0&&b<BUTTON_CAPACITY&&buttons[b]?LWCGL_TRUE:LWCGL_FALSE;}
static const char*button_name(int b){static _Thread_local char name[24];if(b<0||b>=BUTTON_CAPACITY)return NULL;snprintf(name,sizeof name,"BUTTON%d",b);return name;}static int button_index(const char*name){int b=-1;if(name&&sscanf(name,"BUTTON%d",&b)==1&&b>=0&&b<BUTTON_CAPACITY)return b;return -1;}static int button_count(void){return GLFW_MOUSE_BUTTON_LAST+1;}static LWCGLbool has_wheel(void){return LWCGL_TRUE;}
static LWCGLbool next(void){if(read_pos==write_pos)return LWCGL_FALSE;current=events[read_pos];read_pos=(read_pos+1u)%EVENT_CAPACITY;return LWCGL_TRUE;}static int event_button(void){return current.button;}static LWCGLbool event_state(void){return current.state;}static int event_dx(void){return current.dx;}static int event_dy(void){return current.dy;}static int event_x(void){return current.x;}static int event_y(void){return current.y;}static int event_wheel(void){return current.wheel;}static uint64_t event_nanos(void){return current.nanos;}
static int get_x(void){return public_x(mouse_x);}static int get_y(void){return public_y(mouse_y);}static int get_dx(void){return whole(&dx_accum);}static int get_dy(void){return whole(&dy_accum);}static int get_wheel(void){return whole(&wheel_accum);}static LWCGLbool is_grabbed(void){return grabbed;}
static void set_grabbed(LWCGLbool v){grabbed=v?LWCGL_TRUE:LWCGL_FALSE;dx_accum=dy_accum=event_dx_frac=event_dy_frac=0;have_position=LWCGL_FALSE;GLFWwindow*win=w();if(win)glfwSetInputMode(win,GLFW_CURSOR,grabbed?GLFW_CURSOR_DISABLED:GLFW_CURSOR_NORMAL);}
static void set_position(int x,int y){GLFWwindow*win=w();if(!win)return;int ww=1,wh=1,fw=Display.getWidth(),fh=Display.getHeight();glfwGetWindowSize(win,&ww,&wh);if(fw<=0)fw=1;if(fh<=0)fh=1;double wx=(double)x*(double)ww/(double)fw,wy=(double)(fh-1-y)*(double)wh/(double)fh;ignore_cursor=LWCGL_TRUE;glfwSetCursorPos(win,wx,wy);mouse_x=wx;mouse_y=wy;have_position=LWCGL_TRUE;}
static void set_clip(LWCGLbool v){clip=v?LWCGL_TRUE:LWCGL_FALSE;}static LWCGLbool is_clip(void){return clip;}uint64_t lwcglMouseDroppedEvents(void){return dropped;}
const MouseAPI Mouse={22,create_mouse,destroy_mouse,is_created,poll,button_down,button_name,button_index,button_count,has_wheel,next,event_button,event_state,event_dx,event_dy,event_x,event_y,event_wheel,event_nanos,get_x,get_y,get_dx,get_dy,get_wheel,is_grabbed,set_grabbed,set_position,set_clip,is_clip,sizeof(MouseAPI),LWCGL_ABI_VERSION};
