#include <lwcgl/lwcgl.h>
#include "lwcgl_internal.h"
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <stdatomic.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_CONTEXTS 128u
#define MAX_PROCS 192u
typedef struct ContextSlot { void *context; uint64_t generation; } ContextSlot;
typedef struct ProcEntry { const char *name; GLFWglproc proc; } ProcEntry;
typedef struct CapInternal { size_t count; ProcEntry entries[MAX_PROCS]; } CapInternal;
static ContextSlot contexts[MAX_CONTEXTS]; static atomic_flag context_lock=ATOMIC_FLAG_INIT; static atomic_uint_fast64_t next_generation=1;
static LWCGL_THREAD_LOCAL GLCapabilities *selected;
LWCGL_THREAD_LOCAL GL11API GL11; LWCGL_THREAD_LOCAL GL12API GL12; LWCGL_THREAD_LOCAL GL13API GL13; LWCGL_THREAD_LOCAL GL14API GL14; LWCGL_THREAD_LOCAL GL15API GL15; LWCGL_THREAD_LOCAL GL20API GL20; LWCGL_THREAD_LOCAL GL21API GL21; LWCGL_THREAD_LOCAL GL30API GL30; LWCGL_THREAD_LOCAL GL31API GL31; LWCGL_THREAD_LOCAL GL32API GL32; LWCGL_THREAD_LOCAL GL33API GL33; LWCGL_THREAD_LOCAL GL40API GL40; LWCGL_THREAD_LOCAL GL41API GL41; LWCGL_THREAD_LOCAL GL42API GL42; LWCGL_THREAD_LOCAL GL43API GL43; LWCGL_THREAD_LOCAL GL44API GL44; LWCGL_THREAD_LOCAL GL45API GL45; LWCGL_THREAD_LOCAL GL46API GL46;
static void lock_contexts(void){while(atomic_flag_test_and_set_explicit(&context_lock,memory_order_acquire)){};} static void unlock_contexts(void){atomic_flag_clear_explicit(&context_lock,memory_order_release);}
static void clear_tables(void){memset(&GL11,0,sizeof GL11);memset(&GL12,0,sizeof GL12);memset(&GL13,0,sizeof GL13);memset(&GL14,0,sizeof GL14);memset(&GL15,0,sizeof GL15);memset(&GL20,0,sizeof GL20);memset(&GL21,0,sizeof GL21);memset(&GL30,0,sizeof GL30);memset(&GL31,0,sizeof GL31);memset(&GL32,0,sizeof GL32);memset(&GL33,0,sizeof GL33);memset(&GL40,0,sizeof GL40);memset(&GL41,0,sizeof GL41);memset(&GL42,0,sizeof GL42);memset(&GL43,0,sizeof GL43);memset(&GL44,0,sizeof GL44);memset(&GL45,0,sizeof GL45);memset(&GL46,0,sizeof GL46);}
static void apply(const GLCapabilities*c){if(!c){clear_tables();return;}GL11=c->GL11;GL12=c->GL12;GL13=c->GL13;GL14=c->GL14;GL15=c->GL15;GL20=c->GL20;GL21=c->GL21;GL30=c->GL30;GL31=c->GL31;GL32=c->GL32;GL33=c->GL33;GL40=c->GL40;GL41=c->GL41;GL42=c->GL42;GL43=c->GL43;GL44=c->GL44;GL45=c->GL45;GL46=c->GL46;}
void lwcglGLRegisterContext(void*ctx){if(!ctx)return;lock_contexts();for(size_t i=0;i<MAX_CONTEXTS;i++)if(contexts[i].context==ctx){unlock_contexts();return;}for(size_t i=0;i<MAX_CONTEXTS;i++)if(!contexts[i].context){contexts[i].context=ctx;contexts[i].generation=atomic_fetch_add_explicit(&next_generation,1,memory_order_relaxed);break;}unlock_contexts();}
uint64_t lwcglGLContextGeneration(void*ctx){if(!ctx)return 0;uint64_t g=0;lock_contexts();for(size_t i=0;i<MAX_CONTEXTS;i++)if(contexts[i].context==ctx){g=contexts[i].generation;break;}unlock_contexts();return g;}
void lwcglGLUnregisterContext(void*ctx){if(!ctx)return;lock_contexts();for(size_t i=0;i<MAX_CONTEXTS;i++)if(contexts[i].context==ctx){contexts[i].context=NULL;contexts[i].generation=0;break;}unlock_contexts();if(selected&&selected->context==ctx){selected=NULL;clear_tables();}}
void lwcglGLInvalidateAllContexts(void){lock_contexts();memset(contexts,0,sizeof contexts);atomic_fetch_add_explicit(&next_generation,1,memory_order_relaxed);unlock_contexts();selected=NULL;clear_tables();}
void lwcglGLContextChanged(void*ctx){if(!ctx){selected=NULL;clear_tables();return;}uint64_t g=lwcglGLContextGeneration(ctx);if(!g){lwcglGLRegisterContext(ctx);g=lwcglGLContextGeneration(ctx);}if(selected&&(selected->context!=ctx||selected->contextGeneration!=g)){selected=NULL;clear_tables();}}
static int atleast(int major,int minor,int rmaj,int rmin){return major>rmaj||(major==rmaj&&minor>=rmin);}
static void proc_to_slot(void*slot,size_t slot_size,GLFWglproc proc){memset(slot,0,slot_size);if(proc){size_t n=slot_size<sizeof proc?slot_size:sizeof proc;memcpy(slot,&proc,n);}}
static int load(GLCapabilities*c,void*slot,size_t slot_size,const char*name,int intro_major,int intro_minor){GLFWglproc p=glfwGetProcAddress(name);CapInternal*in=(CapInternal*)c->internal;if(in&&in->count<MAX_PROCS)in->entries[in->count++]=(ProcEntry){name,p};proc_to_slot(slot,slot_size,p);if(atleast(c->major,c->minor,intro_major,intro_minor)&&!p){char m[192];snprintf(m,sizeof m,"GL.createCapabilities: required function %s is unavailable",name);lwcglSetErrorInternal(LWCGL_ERROR_UNSUPPORTED,m);return -1;}return 0;}
#define LOAD(g,m,a,b) do{if(load(c,&c->g.m,sizeof c->g.m,#m,a,b))goto fail;}while(0)
static void flags(GLCapabilities*c){c->OpenGL11=atleast(c->major,c->minor,1,1);c->OpenGL12=atleast(c->major,c->minor,1,2);c->OpenGL13=atleast(c->major,c->minor,1,3);c->OpenGL14=atleast(c->major,c->minor,1,4);c->OpenGL15=atleast(c->major,c->minor,1,5);c->OpenGL20=atleast(c->major,c->minor,2,0);c->OpenGL21=atleast(c->major,c->minor,2,1);c->OpenGL30=atleast(c->major,c->minor,3,0);c->OpenGL31=atleast(c->major,c->minor,3,1);c->OpenGL32=atleast(c->major,c->minor,3,2);c->OpenGL33=atleast(c->major,c->minor,3,3);c->OpenGL40=atleast(c->major,c->minor,4,0);c->OpenGL41=atleast(c->major,c->minor,4,1);c->OpenGL42=atleast(c->major,c->minor,4,2);c->OpenGL43=atleast(c->major,c->minor,4,3);c->OpenGL44=atleast(c->major,c->minor,4,4);c->OpenGL45=atleast(c->major,c->minor,4,5);c->OpenGL46=atleast(c->major,c->minor,4,6);}
static GLCapabilities*create_caps(void){lwcglClearError();GLFWwindow*ctx=glfwGetCurrentContext();if(!ctx){lwcglSetErrorInternal(LWCGL_ERROR_NO_CONTEXT,"GL.createCapabilities: no current context");return NULL;}lwcglGLContextChanged(ctx);uint64_t gen=lwcglGLContextGeneration(ctx);GLCapabilities*c=(GLCapabilities*)calloc(1,sizeof*c);CapInternal*in=(CapInternal*)calloc(1,sizeof*in);if(!c||!in){free(c);free(in);lwcglSetErrorInternal(LWCGL_ERROR_OUT_OF_MEMORY,"GL.createCapabilities: allocation failed");return NULL;}c->abiSize=sizeof*c;c->abiVersion=LWCGL_ABI_VERSION;c->context=ctx;c->contextGeneration=gen;c->internal=in;
    GLFWglproc gs=glfwGetProcAddress("glGetString");proc_to_slot(&c->GL11.glGetString,sizeof c->GL11.glGetString,gs);if(in->count<MAX_PROCS)in->entries[in->count++]=(ProcEntry){"glGetString",gs};if(!c->GL11.glGetString){lwcglSetErrorInternal(LWCGL_ERROR_UNSUPPORTED,"GL.createCapabilities: glGetString is unavailable");goto fail;}const LWCGLubyte*vs=c->GL11.glGetString(LWCGL_GL_VERSION);if(!vs||sscanf((const char*)vs,"%d.%d",&c->major,&c->minor)!=2){lwcglSetErrorInternal(LWCGL_ERROR_NATIVE,"GL.createCapabilities: invalid GL_VERSION");goto fail;}flags(c);
    LOAD(GL11,glClear,1,0);LOAD(GL11,glClearColor,1,0);LOAD(GL11,glClearDepth,1,0);LOAD(GL11,glViewport,1,0);LOAD(GL11,glScissor,1,0);LOAD(GL11,glEnable,1,0);LOAD(GL11,glDisable,1,0);LOAD(GL11,glIsEnabled,1,0);LOAD(GL11,glBlendFunc,1,0);LOAD(GL11,glDepthFunc,1,0);LOAD(GL11,glDepthMask,1,0);LOAD(GL11,glColorMask,1,0);LOAD(GL11,glCullFace,1,0);LOAD(GL11,glFrontFace,1,0);LOAD(GL11,glPolygonMode,1,0);LOAD(GL11,glLineWidth,1,0);LOAD(GL11,glPointSize,1,0);LOAD(GL11,glDrawArrays,1,1);LOAD(GL11,glDrawElements,1,1);LOAD(GL11,glGenTextures,1,1);LOAD(GL11,glDeleteTextures,1,1);LOAD(GL11,glBindTexture,1,1);LOAD(GL11,glTexParameteri,1,1);LOAD(GL11,glTexParameterf,1,1);LOAD(GL11,glTexImage2D,1,1);LOAD(GL11,glTexSubImage2D,1,1);LOAD(GL11,glGetBooleanv,1,1);LOAD(GL11,glGetIntegerv,1,1);LOAD(GL11,glGetFloatv,1,1);LOAD(GL11,glGetError,1,1);LOAD(GL11,glReadPixels,1,1);LOAD(GL11,glPixelStorei,1,1);
    LOAD(GL12,glDrawRangeElements,1,2);LOAD(GL12,glTexImage3D,1,2);LOAD(GL12,glTexSubImage3D,1,2);LOAD(GL13,glActiveTexture,1,3);LOAD(GL13,glSampleCoverage,1,3);LOAD(GL13,glCompressedTexImage2D,1,3);LOAD(GL14,glBlendEquation,1,4);LOAD(GL14,glBlendFuncSeparate,1,4);LOAD(GL14,glPointParameterf,1,4);LOAD(GL14,glPointParameterfv,1,4);
    LOAD(GL15,glGenBuffers,1,5);LOAD(GL15,glDeleteBuffers,1,5);LOAD(GL15,glBindBuffer,1,5);LOAD(GL15,glBufferData,1,5);LOAD(GL15,glBufferSubData,1,5);LOAD(GL15,glGetBufferSubData,1,5);LOAD(GL15,glMapBuffer,1,5);LOAD(GL15,glUnmapBuffer,1,5);LOAD(GL15,glGenQueries,1,5);LOAD(GL15,glDeleteQueries,1,5);LOAD(GL15,glBeginQuery,1,5);LOAD(GL15,glEndQuery,1,5);LOAD(GL15,glGetQueryObjectuiv,1,5);
    LOAD(GL20,glCreateShader,2,0);LOAD(GL20,glShaderSource,2,0);LOAD(GL20,glCompileShader,2,0);LOAD(GL20,glGetShaderiv,2,0);LOAD(GL20,glGetShaderInfoLog,2,0);LOAD(GL20,glDeleteShader,2,0);LOAD(GL20,glCreateProgram,2,0);LOAD(GL20,glAttachShader,2,0);LOAD(GL20,glDetachShader,2,0);LOAD(GL20,glLinkProgram,2,0);LOAD(GL20,glValidateProgram,2,0);LOAD(GL20,glGetProgramiv,2,0);LOAD(GL20,glGetProgramInfoLog,2,0);LOAD(GL20,glUseProgram,2,0);LOAD(GL20,glDeleteProgram,2,0);LOAD(GL20,glGetUniformLocation,2,0);LOAD(GL20,glUniform1i,2,0);LOAD(GL20,glUniform1f,2,0);LOAD(GL20,glUniform2f,2,0);LOAD(GL20,glUniform3f,2,0);LOAD(GL20,glUniform4f,2,0);LOAD(GL20,glUniformMatrix4fv,2,0);LOAD(GL20,glGetAttribLocation,2,0);LOAD(GL20,glBindAttribLocation,2,0);LOAD(GL20,glEnableVertexAttribArray,2,0);LOAD(GL20,glDisableVertexAttribArray,2,0);LOAD(GL20,glVertexAttribPointer,2,0);LOAD(GL20,glDrawBuffers,2,0);
    LOAD(GL21,glUniformMatrix2x3fv,2,1);LOAD(GL21,glUniformMatrix3x2fv,2,1);
    LOAD(GL30,glGenVertexArrays,3,0);LOAD(GL30,glDeleteVertexArrays,3,0);LOAD(GL30,glBindVertexArray,3,0);LOAD(GL30,glIsVertexArray,3,0);LOAD(GL30,glMapBufferRange,3,0);LOAD(GL30,glFlushMappedBufferRange,3,0);LOAD(GL30,glGenFramebuffers,3,0);LOAD(GL30,glDeleteFramebuffers,3,0);LOAD(GL30,glBindFramebuffer,3,0);LOAD(GL30,glCheckFramebufferStatus,3,0);LOAD(GL30,glFramebufferTexture2D,3,0);LOAD(GL30,glFramebufferTextureLayer,3,0);LOAD(GL30,glGenRenderbuffers,3,0);LOAD(GL30,glDeleteRenderbuffers,3,0);LOAD(GL30,glBindRenderbuffer,3,0);LOAD(GL30,glRenderbufferStorage,3,0);LOAD(GL30,glFramebufferRenderbuffer,3,0);LOAD(GL30,glGenerateMipmap,3,0);LOAD(GL30,glBlitFramebuffer,3,0);LOAD(GL30,glRenderbufferStorageMultisample,3,0);LOAD(GL30,glBindBufferBase,3,0);LOAD(GL30,glBindBufferRange,3,0);LOAD(GL30,glGetStringi,3,0);
    LOAD(GL31,glDrawArraysInstanced,3,1);LOAD(GL31,glDrawElementsInstanced,3,1);LOAD(GL31,glCopyBufferSubData,3,1);LOAD(GL31,glGetUniformBlockIndex,3,1);LOAD(GL31,glUniformBlockBinding,3,1);LOAD(GL32,glFenceSync,3,2);LOAD(GL32,glIsSync,3,2);LOAD(GL32,glDeleteSync,3,2);LOAD(GL32,glClientWaitSync,3,2);LOAD(GL32,glWaitSync,3,2);LOAD(GL32,glDrawElementsBaseVertex,3,2);LOAD(GL33,glVertexAttribDivisor,3,3);LOAD(GL33,glGenSamplers,3,3);LOAD(GL33,glDeleteSamplers,3,3);LOAD(GL33,glBindSampler,3,3);LOAD(GL33,glSamplerParameteri,3,3);LOAD(GL33,glQueryCounter,3,3);LOAD(GL33,glGetQueryObjectui64v,3,3);
    LOAD(GL40,glDrawArraysIndirect,4,0);LOAD(GL40,glDrawElementsIndirect,4,0);LOAD(GL40,glPatchParameteri,4,0);LOAD(GL40,glBlendEquationi,4,0);LOAD(GL40,glBlendFunci,4,0);LOAD(GL41,glGenProgramPipelines,4,1);LOAD(GL41,glDeleteProgramPipelines,4,1);LOAD(GL41,glBindProgramPipeline,4,1);LOAD(GL41,glUseProgramStages,4,1);LOAD(GL41,glProgramUniform1i,4,1);LOAD(GL41,glProgramUniform1f,4,1);LOAD(GL41,glProgramUniformMatrix4fv,4,1);LOAD(GL41,glShaderBinary,4,1);LOAD(GL42,glMemoryBarrier,4,2);LOAD(GL42,glTexStorage1D,4,2);LOAD(GL42,glTexStorage2D,4,2);LOAD(GL42,glTexStorage3D,4,2);LOAD(GL42,glBindImageTexture,4,2);LOAD(GL43,glDispatchCompute,4,3);LOAD(GL43,glDispatchComputeIndirect,4,3);LOAD(GL43,glDebugMessageCallback,4,3);LOAD(GL43,glDebugMessageControl,4,3);LOAD(GL43,glObjectLabel,4,3);LOAD(GL43,glMultiDrawArraysIndirect,4,3);LOAD(GL43,glMultiDrawElementsIndirect,4,3);LOAD(GL44,glBufferStorage,4,4);LOAD(GL44,glBindBuffersBase,4,4);LOAD(GL44,glBindTextures,4,4);LOAD(GL44,glBindSamplers,4,4);LOAD(GL44,glClearTexImage,4,4);LOAD(GL45,glCreateBuffers,4,5);LOAD(GL45,glNamedBufferData,4,5);LOAD(GL45,glNamedBufferStorage,4,5);LOAD(GL45,glNamedBufferSubData,4,5);LOAD(GL45,glCreateVertexArrays,4,5);LOAD(GL45,glCreateTextures,4,5);LOAD(GL45,glTextureStorage2D,4,5);LOAD(GL45,glTextureSubImage2D,4,5);LOAD(GL45,glBindTextureUnit,4,5);LOAD(GL45,glCreateFramebuffers,4,5);LOAD(GL45,glNamedFramebufferTexture,4,5);LOAD(GL45,glCheckNamedFramebufferStatus,4,5);LOAD(GL45,glClipControl,4,5);LOAD(GL46,glSpecializeShader,4,6);LOAD(GL46,glMultiDrawArraysIndirectCount,4,6);LOAD(GL46,glMultiDrawElementsIndirectCount,4,6);
    selected=c;apply(c);return c;
fail: free(in);free(c);return NULL;}
#undef LOAD
static void destroy_caps(GLCapabilities*c){lwcglClearError();if(!c)return;if(selected==c){selected=NULL;clear_tables();}free(c->internal);memset(c,0,sizeof*c);free(c);}
static int valid_selected(GLCapabilities*c){if(!c)return 0;void*ctx=glfwGetCurrentContext();uint64_t gen=lwcglGLContextGeneration(ctx);return ctx&&c->context==ctx&&gen&&c->contextGeneration==gen;}
static GLCapabilities*get_caps(void){if(selected&&!valid_selected(selected)){selected=NULL;clear_tables();lwcglSetErrorInternal(LWCGL_ERROR_CONTEXT_MISMATCH,"GL.getCapabilities: selected capabilities do not belong to current context");}return selected;}
static int set_caps(GLCapabilities*c){lwcglClearError();if(!c){selected=NULL;clear_tables();return 0;}if(c->abiVersion!=LWCGL_ABI_VERSION||c->abiSize!=sizeof*c){lwcglSetErrorInternal(LWCGL_ERROR_STATE,"GL.setCapabilities: ABI mismatch");return -1;}if(!valid_selected(c)){lwcglSetErrorInternal(LWCGL_ERROR_CONTEXT_MISMATCH,"GL.setCapabilities: capabilities do not belong to current context");return -1;}selected=c;apply(c);return 0;}
static GLFWglproc find_proc(const GLCapabilities*c,const char*name){if(!c||!name)return NULL;CapInternal*in=(CapInternal*)c->internal;for(size_t i=0;i<in->count;i++)if(strcmp(in->entries[i].name,name)==0)return in->entries[i].proc;return NULL;}
static void*get_addr(const char*name){lwcglClearError();GLCapabilities*c=get_caps();if(!c||!name)return NULL;GLFWglproc p=find_proc(c,name);void*out=NULL;if(p){size_t n=sizeof out<sizeof p?sizeof out:sizeof p;memcpy(&out,&p,n);}return out;}
static LWCGLbool is_avail(const char*name){lwcglClearError();GLCapabilities*c=get_caps();return c&&name&&find_proc(c,name)?LWCGL_TRUE:LWCGL_FALSE;}
static LWCGLbool ext_avail(const char*name){lwcglClearError();if(!name||!glfwGetCurrentContext())return LWCGL_FALSE;return glfwExtensionSupported(name)?LWCGL_TRUE:LWCGL_FALSE;}
const GLAPI GL={sizeof(GLAPI),LWCGL_ABI_VERSION,create_caps,destroy_caps,get_caps,set_caps,get_addr,is_avail,ext_avail};
