name: verify
on:
  workflow_dispatch:
concurrency:
  group: lwcgl-v3-verify-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y libglfw3-dev xvfb pkg-config
      - name: Verify
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
        run: xvfb-run -a make clean check
  sanitizer:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y libglfw3-dev xvfb pkg-config clang
      - run: xvfb-run -a make CC=clang CXX=clang++ sanitize
  macos:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install pkg-config glfw
      - run: make clean check
