name: build

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglfw3-dev pkg-config
      - name: Build and test lwcgl
        run: make check

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install pkg-config glfw
      - name: Build and test lwcgl
        run: make check
